# Enable Colours
set -g default-terminal 'tmux-256color'
set -as terminal-overrides ',xterm*:Tc'

# Prefix Key
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Open new windows in current directory path
bind c new-window -c "#{pane_current_path}"

# Split Windows
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Reload Config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "󰑓 Config reloaded"

# Resize Panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z

# Enable Mouse
set -g mouse on

# Scrollback
set -g history-limit 50000

# Clipboard
set -g set-clipboard on

# VIM motions
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Enable Mouse Dragging
unbind -T copy-mode-vi MouseDragEnd1Pane

# Status Line Position
set-option -g status-position top

##### Neovim CheckHealth Recommendations #####
set-option -sg escape-time 10
set-option -g focus-events on

##### Plugins #####
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

##### Theme #####
set -g @plugin 'Nybkox/tmux-ukiyo'
set -g @ukiyo-theme "kanagawa/wave"
set -g @ukiyo-ignore-window-colors true

##### Persist Sessions #####
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-processes 'nvim'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'

##### Pop-Up: Session List #####
bind w display-popup -E -w 80% -h 80% ~/.config/tmux/scripts/tmux-menu.sh

##### Pop-Up: LazyGit #####
bind g display-popup -d "#{pane_current_path}" -E -w 80% -h 80% -E lazygit

##### TPM Init #####
run '~/.tmux/plugins/tpm/tpm'
